project:
  type: book
  output-dir: docs

book:
  title: "The Dyanmics of Basketball"
  author: "Brandon Scott"
  date: "02/22/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_1.ipynb
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cyborg
  pdf:
    documentclass: scrreprt



