project:
  type: book
  output-dir: docs

book:
  title: "Systematic Coaching: The Power of Mathematical Thinking in Basketball"
  author: "Brandon Scott"
  date: "12/07/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_1.ipynb
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cyborg
  pdf:
    documentclass: scrreprt



